{{- if and (hasKey .Values "objectStore") .Values.objectStore.createSecret .Values.objectStore.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos.objectStoreSecretName" . }}
  namespace: {{ include "thanos.namespace" . }}
  labels:
{{ include "thanos.commonLabels" . | indent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{ toYaml .Values.commonAnnotations | indent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ default "objstore.yml" .Values.objectStore.key }}: |-
{{ tpl .Values.objectStore.config . | indent 4 }}
{{- end }}
