apiVersion: v2
name: thanos
description: Managed Thanos deployment for compactor, query, query-frontend and storegateway components.
type: application
version: 0.1.4
appVersion: 0.40.1
maintainers:
  - name: rayselfs
    email: rayselfs@gmail.com
    url: https://github.com/rayselfs
keywords:
  - thanos
  - prometheus
  - metrics
  - observability
sources:
  - https://github.com/thanos-io/thanos
