apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-ec2-runtime-checker.fullname" . }}-config
  labels:
    {{- include "aws-ec2-runtime-checker.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.targets | toJson }}
