{{- if eq .Values.kind "Deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-ec2-runtime-checker.fullname" . }}
  labels:
    {{- include "aws-ec2-runtime-checker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-ec2-runtime-checker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aws-ec2-runtime-checker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aws-ec2-runtime-checker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["cron"]
          env:
            - name: LEADER_ELECTION_ENABLED
              value: {{ .Values.leaderElection.enabled | quote }}
            - name: LEASE_NAME
              value: {{ .Values.leaderElection.leaseName | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            {{- if .Values.aws.accessKeyId }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId | quote }}
            {{- end }}
            {{- if .Values.aws.secretAccessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey | quote }}
            {{- end }}
            - name: DRY_RUN
              value: {{ .Values.dryRun | quote }}
            - name: CONFIG_PATH
              value: "/app/config/config.json"
            - name: SCHEDULE
              value: {{ .Values.schedule | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "aws-ec2-runtime-checker.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
