{{- if and (eq .Values.kind "Deployment") .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aws-ec2-runtime-checker.fullname" . }}-leader-election
  labels:
    {{- include "aws-ec2-runtime-checker.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
{{- end }}
