{{- if and (eq .Values.kind "Deployment") .Values.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aws-ec2-runtime-checker.fullname" . }}-leader-election
  labels:
    {{- include "aws-ec2-runtime-checker.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ec2-runtime-checker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aws-ec2-runtime-checker.fullname" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io
{{- end }}
